### PR TITLE
Transpilation into Kotlin.

### PR DESCRIPTION
**Pull request by dkorolev**
Do not merge yet.

With the first commit, the `tests/smoke/sum/policy.rego` test passes in Kotlin, in semi-manual conjunction with my `{gradle-devenv}` from [simple-kotlin](https://github.com/dkorolev/simple-kotlin).

A lot more to do, and the "preprocessor file" is far too ugly for this V1, but it's a start.

### CODE REVIEW

**Comment by dkorolev** [comment]
I'll stop at the second commit (and second passing test) for now, but the magic is clearly working!

**Comment by dkorolev** [comment]
Status update.

Remains:

* Working with `Array`-s.
* Working with `Set`-s.
* Working with `ScanStmt()` (this one _might_ be tough, so not today).
* Renaming of various internal things.
* Remove the dependency on `dkorolev/simple-kotlin` cloned under `..` for test runs (yes, temporary, of course).
* A Github action to run Kotlin tests too.
* Scripts cleanup.

Progress:

* Houston, we got [142 Kotlin tests passing](https://github.com/dkorolev/simple-kotlin/actions/runs/6074884828/job/16479895479) (out of [157 total in JS](https://github.com/dkorolev/asbyrgi/actions/runs/6074887896/job/16479904856)).
* To be clear: the remaining tests are not failing, they are just not ported yet.

I may not find much time for this this week though. Fingers crossed!

**Comment by dkorolev** [comment]
Milestone: as per https://github.com/dkorolev/asbyrgi/commit/a0f9146079e58b9e1a859cbdfa618191682f2a9b, both [JS](https://github.com/dkorolev/asbyrgi/actions/runs/6096965718/job/16543636859) and [Kotlin](https://github.com/dkorolev/asbyrgi/actions/runs/6096965723/job/16543636892) tests pass, all 157 of them.

**Review by mzhurovich — APPROVED** [review]
👍

**Comment by dkorolev** [comment]
I'd say let's declare V1 complete at this point!

**Pull request merged**
